### ISSUE TITLE
Fatal signal 11 on domoticz beta caused by use of positional parameter in plugin.py

### ISSUE THREAD

**Issue by rwaaren** [gerard33/sonos#5]
triggered by the description on Github (domoticz/domoticz#2092), I changed line 696 plugin.py of the sonos plugin.

<comment> # old line with positional parameters this line will trigger a fatal signal 11 on my system
Devices[Unit].Update(nValue, str(sValue))

<comment> # New line with named parameters
Devices[Unit].Update(nValue=nValue, sValue=str(sValue))

With this change my local compiled domoticz keeps running.

**Comment by gerard33** [comment]
Thanks, I have changed it in 80cc64f.

As of now this script will no longer be maintained. So for any other changed you can just fork this repo.
