### ISSUE TITLE
Errors with the plugin

### ISSUE THREAD

**Issue by Falken82** [gerard33/sonos#6]
The only thing that could get my Domoticz back to life was to manually remove the files created by this code. 

Some of the files are impossible to remove. And some of my domoticz switches are still broken as of today, all because of this.

**Comment by gerard33** [comment]
Very annoying that your Domoticz is broken, but the Python plugin part can't brake any switches in Domoticz. Also removing files is something that your OS is taking care of, that has nothing to do with Domoticz or the scripts of this plugin. Hopefully you are able to restore Domoticz again. For any further help you can check the forums of Domoticz.
